Entity/TextItem.php
<?php

declare(strict_types=1);

namespace Monolith\Module\Texter\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Smart\CoreBundle\Doctrine\ColumnTrait;

/**
 * @ORM\Entity
 * @ORM\Table(name="texter_items",
 *      indexes={
 *          @ORM\Index(columns={"created_at"}),
 *      }
 * )
 */
class TextItem
{
    use ColumnTrait\Id;
    use ColumnTrait\CreatedAt;
    use ColumnTrait\UpdatedAt;
    use ColumnTrait\Text;
    use ColumnTrait\FosUser;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=8, nullable=true)
     */
    protected $locale;

    /**
     * @var int
     *
     * @ORM\Column(type="smallint")
     */
    protected $editor;

    /**
     * @var array
     *
     * @ORM\Column(type="array")
     */
    protected $meta;

    /**
     * @var TextItemHistory[]|ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="TextItemHistory", mappedBy="item", cascade={"persist", "remove"}, fetch="EXTRA_LAZY")
     */
    protected $history;

    /**
     * TextItem constructor.
     */
    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->locale   = 'ru';
        $this->meta     = [];
        $this->text     = null;
        $this->editor   = 1;
        $this->history  = new ArrayCollection();
    }

    /**
     * @return string
     */
    public function __toString(): string
    {
        return $this->getText();
    }

    /**
     * @return string
     */
    public function getAnnounce(): string
    {
        $a = strip_tags((string) $this->text);

        $dotted = (mb_strlen($a, 'utf-8') > 100) ? '...' : '';

        return mb_substr($a, 0, 100, 'utf-8').$dotted;
    }

    /**
     * @param int $editor
     *
     * @return $this
     */
    public function setEditor(int $editor): TextItem
    {
        $this->editor = $editor;

        return $this;
    }

    /**
     * @return int
     */
    public function getEditor(): int
    {
        return $this->editor;
    }

    /**
     * @param string $locale
     *
     * @return $this
     */
    public function setLocale($locale)
    {
        $this->locale = $locale;

        return $this;
    }

    /**
     * @return string
     */
    public function getLocale()
    {
        return $this->locale;
    }

    /**
     * @return array
     */
    public function getMeta()
    {
        return empty($this->meta) ? [] : $this->meta;
    }

    /**
     * @param array $meta
     *
     * @return $this
     */
    public function setMeta(array $meta)
    {
        if (is_array($meta)) {
            foreach ($meta as $key => $value) {
                if (empty($value)) {
                    unset($meta[$key]);
                }
            }
        } else {
            $this->meta = [];
        }

        $this->meta = $meta;

        return $this;
    }

    /**
     * @return TextItemHistory[]|ArrayCollection
     */
    public function getHistory()
    {
        return $this->history;
    }

    /**
     * @param TextItemHistory[]|ArrayCollection $history
     *
     * @return $this
     */
    public function setHistory($history)
    {
        $this->history = $history;

        return $this;
    }
}

Resources/views/Admin/_codemirror.html.twig
{% extends '@TexterModule/Admin/index.html.twig' %}

{% block styles %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('bundles/felib/codemirror/lib/codemirror.css') }}">
    <link rel="stylesheet" href="{{ asset('bundles/felib/codemirror/addon/hint/show-hint.css') }}">
    <link rel="stylesheet" href="{{ asset('bundles/felib/codemirror/addon/display/fullscreen.css') }}">
    <link rel="stylesheet" href="{{ asset('bundles/felib/codemirror/theme/cobalt.css') }}">
    <style media="all" type="text/css">
        .CodeMirror {
            height: 530px;
        }
        .CodeMirror * {
            font-family: "Consolas", "Bitstream Vera Sans Mono", "Courier New", Courier, monospace;
            font-size: 16px;
        }
        .CodeMirror-fullscreen {
            z-index: 9999;
        }
    </style>
{% endblock %}

{% block scripts %}
    {{ parent() }}
    <script src="{{ asset('bundles/felib/codemirror/lib/codemirror.js') }}"></script>
    <script src="{{ asset('bundles/felib/codemirror/addon/display/fullscreen.js') }}"></script>
    <script src="{{ asset('bundles/felib/codemirror/addon/edit/closetag.js') }}"></script>
    <script src="{{ asset('bundles/felib/codemirror/addon/fold/xml-fold.js') }}"></script>
    <script src="{{ asset('bundles/felib/codemirror/addon/hint/show-hint.js') }}"></script>
    <script src="{{ asset('bundles/felib/codemirror/addon/hint/xml-hint.js') }}"></script>
    <script src="{{ asset('bundles/felib/codemirror/addon/hint/html-hint.js') }}"></script>
    <script src="{{ asset('bundles/felib/codemirror/addon/selection/active-line.js') }}"></script>
    <script src="{{ asset('bundles/felib/codemirror/mode/xml/xml.js') }}"></script>
    <script src="{{ asset('bundles/felib/codemirror/mode/javascript/javascript.js') }}"></script>
    <script src="{{ asset('bundles/felib/codemirror/mode/css/css.js') }}"></script>
    <script src="{{ asset('bundles/felib/codemirror/mode/htmlmixed/htmlmixed.js') }}"></script>
    <script src="{{ asset('bundles/felib/codemirror/mode/htmlembedded/htmlembedded.js') }}"></script>
{% endblock %}

{% block body_js %}
    {{ parent() }}
    <script type="text/javascript">
        window.onload = function() {
            editor = CodeMirror.fromTextArea(document.getElementById("textarea_ru"), {
                autoCloseTags: true,
                lineNumbers: true,
                styleActiveLine: true,
                matchBrackets: true,
                mode: "text/html",
                theme: "cobalt",
                /*extraKeys: {"Ctrl-Space": "autocomplete"} */
                extraKeys: {
                    "F11": function(cm) {
                        cm.setOption("fullScreen", !cm.getOption("fullScreen"));
                    },
                    "Esc": function(cm) {
                        if (cm.getOption("fullScreen")) cm.setOption("fullScreen", false);
                    }
                }
            });
        };
    </script>
{% endblock body_js %}

Resources/views/Admin/_tinymce.html.twig
{% extends '@TexterModule/Admin/index.html.twig' %}

{% block body_js %}
    {{ parent() }}

    {{ elfinder_tinymce_init4('tinymce4', {'width': 980, 'height': 430, 'title': 'Файловый менеджер' }) }}
    {{ tinymce_init() }}

    <script>
        $('#myTab a').click(function (e) {
            e.preventDefault();
            $(this).tab('show');
            $(this.hash + ' input.focused').focus();
            tinyMCE.get($(this.hash + ' textarea').attr('id')).getBody().focus();
        });

        $().ready(function() {
            var $window = $(window);

            $window.resize(function(){
                var $win_height = $window.height() - 350;

                tinyMCE.activeEditor.theme.resizeTo('100%', $win_height);
            });

            tinyMCE.DOM.setStyle(tinyMCE.DOM.get($('.wysiwyg').attr('id')), 'height', $window.height() - 350 + 'px');
        });
    </script>
{% endblock body_js %}

Resources/views/Admin/edit.html.twig
{% extends item.editor ? '@TexterModule/Admin/_tinymce.html.twig' : '@TexterModule/Admin/_codemirror.html.twig' %}

{% block title %}Редактирование id: {{ item.id }} / Текстер / {{ parent() }}{% endblock %}

{% block styles %}
    {{ parent() }}
    <style media="all" type="text/css">
        body {
            margin-bottom: 0px;
        }
        .tab-content {
            margin-top: 0;
        }
    </style>
{% endblock %}

{% block content %}
    {% if not app.request.query.has('_overlay') %}
        <ul class="nav nav-tabs" id="myTab">
            <li class="active"><a href="#text">Редактор</a></li>
            <li><a href="#meta">Мета-данные</a></li>
            {#<li><a href="#preview">Предпросмотр</a></li>#}
            {#<li><a href="#text_en">Текст (English)</a></li>#}
            {#<li><a href="#history">История правок</a></li>#}
        </ul>
    {% endif %}

    {% if not app.request.query.has('_overlay') %}
        <form action="{{ path('monolith_module.texter.admin.edit', {'id': item.id}) }}" method="post">
    {% else %}
        <form action="" method="post">
    {% endif %}

    <input type="hidden" name="_node_id" value="{{ _node_id }}" />

    <div class="tab-content">
        <div class="tab-pane active" id="text">
            {#<textarea id="textarea_ru" class="tinymce focused wysiwyg" autofocus="autofocus" data-theme="advanced" name="texter[text]" style="width: 96%; height: 780px;" rows="40">{{ item.text|raw }}</textarea>#}
            <textarea id="textarea_ru" class="tinymce focused wysiwyg" autofocus="autofocus" data-theme="advanced" style="height: 100vh" name="texter[text]" style="">{{ item.text|raw }}</textarea>
        </div>
        {#<div class="tab-pane" id="text_en">
            <textarea class="tinymce focused" name="text" style="width: 96%; height: 380px;" rows="20" id="textarea_en">Тут будет текст на енг.</textarea>
        </div>#}
        <div class="tab-pane" id="meta">
            <br>

            <div class="row">
                <div class="span2  col-md-2" style="text-align: right;"><label for="keywords">Keywords</label></div>
                <div class="span10 col-md-10"><input type="text" name="texter[meta][keywords]" id="keywords" value="{% if item.meta.keywords is defined %}{{ item.meta.keywords }}{% endif %}" class="focused input-block-level" /></div>
            </div>

            <br>
            <div class="row">
                <div class="span2  col-md-2" style="text-align: right;"><label for="description">Description</label></div>
                <div class="span10 col-md-10"><input type="text" name="texter[meta][description]" id="description" value="{% if item.meta.description is defined %}{{ item.meta.description }}{% endif %}" class="input-block-level" /></div>
            </div>
        </div>
        {#<div class="tab-pane" id="preview">@todo preview</div>#}
        {#<div class="tab-pane" id="history">@todo history</div>#}
    </div>

    <div class="control-group if-overlay-control-group ">
        <div class="controls">
            <button class="btn btn-success" type="submit" name="submit" value="update" data-cms-button="submit">Сохранить</button>

            {% if not app.request.query.has('_overlay') %}
                {% if app.request.xmlHttpRequest or app.request.query.has('_overlay_debug') %}
                    {# dummy... #}
                {% elseif item._folderPath %}
                    <button class="btn btn-info" type="submit" name="update_and_redirect_to_site" value="update_and_redirect_to_site">Сохранить и перейти на сайт</button>
                {% endif %}
            {% endif %}

            {% if app.request.query.has('redirect_to') %}
                <a class="btn btn-default cms-cancel" data-cms-button="cancel" href="{{ app.request.query.get('redirect_to') }}">Отменить</a>
            {% else %}
                <a class="btn btn-default cms-cancel" data-cms-button="cancel" href="{{ path('monolith_module.texter.admin') }}">Отменить</a>
            {% endif %}
        </div>
    </div>
    </form>

    {% if app.request.query.has('_overlay') %}
        <script>
          document.querySelector('.cms-cancel').addEventListener('click', function (e) {
            e.preventDefault();
            window.top.__closeIframe();
          });
        </script>
        <style>
            .if-overlay-control-group {
                position: fixed;
                z-index: 9999;
                bottom: 0;
                left: 0;
                width: 100%;
                background: #1e282c;
                padding: 10px 0;
                margin: 0px !important;
            }

            .if-overlay-control-group .controls {
                margin: 0;
                display: flex;
                justify-content: center;
            }

            .if-overlay-control-group .controls .btn {
                margin-right: 15px;
            }
        </style>
    {% endif %}
{% endblock content %}

Resources/views/Admin/history.html.twig
{% extends '@TexterModule/Admin/index.html.twig' %}

{% set felib = felib_use('jquery-colorbox') %}

{% block content %}
<div class="box box-primary">
    <div class="box-header with-border">

        <h3>История изменений текста: <a href="{{ path('monolith_module.texter.admin.edit', {'id': item.id}) }}">#{{ item.id }}</a></h3>

        <a href="{{ path('monolith_module.texter.admin') }}">
            <i class="fa fa-arrow-circle-o-left"></i>
            Назад к списку всех текстов.
        </a>

        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>{{ 'Date'|trans }}</th>
                <th>{{ 'Text'|trans }}</th>
                <th>{{ 'Action'|trans }}</th>
            </tr>
            </thead>
            <tbody>
            {% for item in items_history %}
                <tr>
                    <td>{{ item.createdAt|format_datetime }}</td>
                    <td>
                        <a class="history_view_{{ loop.index }}" href="{{ path('monolith_module.texter.admin.history_view', {'id': item.id}) }}">{{ item.announce }}</a>

                        <script>
                            $(document).ready(function(){
                                $('.history_view_{{ loop.index }}').colorbox({
                                    iframe:true,
                                    width:'60%',
                                    initialWidth:'60%',
                                    height:'85%',
                                    initialHeight:'85%',
                                    speed: 100,
                                    fadeOut: 200,
                                    opacity: 0.7
                                });
                            });
                        </script>

                    </td>
                    <td>
                        <a href="{{ path('monolith_module.texter.admin.rollback', {'id': item.id}) }}" title=""><i class="icon-forward"></i><span class="glyphicon glyphicon-forward" aria-hidden="true"></span>Откатить</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
</div>

{% endblock content %}

Resources/views/Admin/history_view.html.twig
{% extends '@Html/base.html.twig' %}

{% set use_libs = {
    'bootstrap': '3',
} %}

{% block body %}
    <div class="wrapper">

        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#html" aria-controls="home" role="tab" data-toggle="tab">HTML</a></li>
            <li role="presentation"><a href="#source" aria-controls="profile" role="tab" data-toggle="tab">Source</a></li>
        </ul>

        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="html">{{ item_history.text }}</div>
            <div role="tabpanel" class="tab-pane" id="source">
                <textarea class="focused" autofocus="autofocus" style="width: 96%;" rows="30">{{ item_history.text|raw }}</textarea>
            </div>
        </div>

    </div>
{% endblock body %}

Resources/views/Admin/index.html.twig
{% extends '@CMS/Admin/module.html.twig' %}

{% block title %}{{ 'Texter'|trans }} / {{ parent() }}{% endblock %}

{% block page_header 'Texter'|trans %}
{% block page_description 'Module'|trans %}

{% block content %}
<div class="box box-primary">
    <div class="box-header with-border">

    <div class="tab-content">
        <div class="tab-pane active" id="all">
            <table class="table table-bordered table-hover">
                <thead>
                <tr>
                    <th>id</th>
                    <th>{{ 'Text'|trans }}</th>
                    <th>{{ 'Folder'|trans }}</th>
                    <th>{{ 'Action'|trans }}</th>
                </tr>
                </thead>
                <tbody>
                {% for item in items %}
                    <tr>
                        <td><a href="{{ path('monolith_module.texter.admin.edit',    {'id': item.id}) }}">{{ item.id }}</a></td>
                        <td><a href="{{ path('monolith_module.texter.admin.edit',    {'id': item.id}) }}">{{ item.announce }}</a></td>
                        <td>{% if item._folderPath %}
                                <small>
                                    <a href="{{ item._folderPath }}" title="Перейти на сайт в раздел: {{ item._folderPath }}">{{ item._folder.title }}</a>
                                </small>
                            {% else %}
                                <span class="label label-danger label-important" title="Этот текст нигде не используется">{{ 'No'|trans }}</span>
                            {% endif %}
                        </td>
                        <td>
                            {% if item.history.count > 0 %}
                                <a href="{{ path('monolith_module.texter.admin.history', {'id': item.id}) }}" title="История"><i class="icon-time"></i><span class="glyphicon glyphicon-time" aria-hidden="true"></span></a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    </div>
</div>
{% endblock content %}